apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

name: build-n-deploy

on:
  push:
    branches:
      - 'main'
jobs:

  build:

    steps:

    - name: Say hello
      uses: docker://golang:1.20.3-alpine3.17
      shell: sh
      run: |
        echo "hello world6"

  #   - uses: cloudbees-io/checkout@v1

  #   - name: build code
  #     uses: docker://golang:1.20.3-alpine3.17
  #     shell: sh
  #     run: |
  #       export GOPATH=$HOME/go
  #       export PATH=$PATH:$GOPATH/bin
  #       go version
  #       CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o build/app-main .

  #   - uses: cloudbees-io/configure-aws-credentials@v0
  #     id: aws-login
  #     with:
  #       aws-region: us-east-1
  #       aws-access-key-id: ${{ vars.cloudbees_saas_test_access_key_id }}
  #       aws-secret-access-key: ${{ secrets.cloudbees_saas_test_secret_access_key }}
  #       role-to-assume: service-ecr-role
  #       role-duration-seconds: "3600" # need to override default of 6h as our role has 1h max

  #   - uses: cloudbees-io/configure-ecr-credentials@v0

  #   - uses: cloudbees-io/kaniko@implicit-dockerconfig
  #     with:
  #       destination: ${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com/hello-go-app-image:latest

  #   - uses: docker://mikefarah/yq:4-githubaction
  #     env:
  #       CHART_REPO: ${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com/hello-go-app-image
  #       CHART_TAG: latest
  #     run: |
  #       yq -i '.image.repository = strenv(CHART_REPO) | .image.tag = strenv(CHART_TAG)' charts/app/values.yaml

  #   - id: helmpkg
  #     name: Package Helm chart
  #     uses: cloudbees-io/helm-package
  #     with:
  #       chart: ./charts/app
  #       destination: ./packaged-charts
  #       version: "0.0.1"

  #   - name: Publish Helm chart
  #     uses: cloudbees-io/helm-push
  #     with:
  #       chart: ${{ steps.helmpkg.outputs.chart }}
  #       remote: oci://${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com

  #   outputs:
  #     chart-location: oci://${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com/hello-go-app
  #     chart-version: "0.0.1"

  # deploy:

  #   needs:
  #     - build

  #   steps:

  #   - uses: cloudbees-io/configure-aws-credentials@v0
  #     with:
  #       aws-region: us-east-1
  #       aws-access-key-id: ${{ vars.cloudbees_saas_test_access_key_id }}
  #       aws-secret-access-key: ${{ secrets.cloudbees_saas_test_secret_access_key }}
  #       role-to-assume: service-eks-role
  #       role-duration-seconds: "3600" # need to override default of 6h as our role has 1h max

  #   - uses: cloudbees-io/configure-eks-credentials@v0
  #     with:
  #       name: arch-saas

  #   - uses: cloudbees-io/configure-ecr-credentials@v0

  #   - uses: docker://alpine/helm:latest
  #     run: |
  #       helm upgrade \
  #         --namespace hello-go-app \
  #         --create-namespace \
  #         --install \
  #         --version ${{ needs.build.outputs.chart-version }} \
  #         app-chart ${{ needs.build.outputs.chart-location }}

